
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.64
distribution_type: module
version: 0.01
name: Module-Math-Depends
author: Adam Kennedy <adamk@cpan.org>
license: perl
build_requires: 
  Test::More: 0.42
requires: 
  perl: 5.005
  Params::Util: 0.10
  version: 0.6701
  Carp: 0
abstract: Convenience object for manipulating module dependencies
